version: 2.1

executors:
  default:
    docker:
      - image: cimg/openjdk:17.0
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

jobs:
  build:
    executor: default
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Obtener Commit SHA
          command: |
            cd ~/project
            echo "Obteniendo el SHA del último commit..."
            GIT_COMMIT=$(git rev-parse HEAD)
            echo "export GIT_COMMIT=${GIT_COMMIT}" >> $BASH_ENV
            echo "Commit SHA filtrado: ${GIT_COMMIT}"

      - run:
          name: Instalar Maven
          command: |
            sudo apt-get update
            sudo apt-get install -y maven

      - run:
          name: Compilar el Proyecto
          command: |
            cd ~/project
            mvn clean install

      - run:
          name: Ejecutar Pruebas
          command: |
            cd ~/project
            mvn test

      - run:
          name: Análisis Estático de Código (Checkstyle)
          command: |
            cd ~/project
            mvn checkstyle:check

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Construir Imagen Docker
          command: |
            cd ~/project
            docker build -t backend-clientes:latest .

      - run:
          name: Ejecutar Contenedor Docker
          command: |
            docker run -d -p 8081:8081 --name backend-app backend-clientes:latest

      - run:
          name: Notificar Éxito en GitHub
          when: on_success
          command: |
            curl -u ${GITHUB_USER}:${GITHUB_TOKEN} \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/robertoo28/BackAppIngenieriaWeb/statuses/${GIT_COMMIT} \
            -d '{
              "state": "success",
              "context": "CI/CD",
              "description": "Build exitoso",
              "target_url": "'"${CIRCLE_BUILD_URL}"'"
            }'

      - run:
          name: Notificar Fallo en GitHub
          when: on_fail
          command: |
            curl -u ${GITHUB_USER}:${GITHUB_TOKEN} \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/robertoo28/BackAppIngenieriaWeb/statuses/${GIT_COMMIT} \
            -d '{
              "state": "failure",
              "context": "CI/CD",
              "description": "Build fallido",
              "target_url": "'"${CIRCLE_BUILD_URL}"'"
            }'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
