version: 2.1

orbs:
  slack: circleci/slack@4.4.0

executors:
  default:
    docker:
      - image: cimg/openjdk:17.0
      - image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: db_springboot_backend
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
      # Añade tus SPRING_DATASOURCE_... variables aquí si es necesario

jobs:
  compile:
    executor: default
    steps:
      - checkout
      - run: mvn clean install -DskipTests

  test:
    executor: default
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Run tests in parallel
          command: mvn test --fail-at-end -Dtest=$(circleci tests split --split-by=timings)

  lint:
    executor: default
    steps:
      - checkout
      - run: mvn checkstyle:check

  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Notificar estado
          command: |
            if [ "$CIRCLE_JOB_STATUS" = "success" ]; then
              echo "Build exitoso. Agrega aquí tu notificación (curl o slack/notify)"
            else
              echo "Build fallido. Agrega aquí tu notificación de fallo"
            fi

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - compile
      - test:
          requires:
            - compile
      - lint:
          requires:
            - test
      - notify:
          requires:
            - lint
